import { module, test } from 'qunit';

module('RequestManager | Error Propagation', function () {
  test('Errors thrown by a handler are catchable by the preceding handler', function (assert) {
    assert.ok(false, 'Not Implemented');
  });

  test('The `request` and `response` on errors is update correctly when an error is not caught by the preceding handler', function (assert) {
    assert.ok(false, 'Not Implemented');
  });

  test('Error documents are meaningfully serializable', function (assert) {
    assert.ok(false, 'Not Implemented');
  });
});
